version: '3.1'

services:
  mongo-db:
    image: mongo:latest
    restart: always
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}